use_frameworks!

target 'LGBCycleScrollView_Example', :exclusive => true do
  pod 'LGBCycleScrollView', :path => '../'
end

target 'LGBCycleScrollView_Tests', :exclusive => true do
  pod 'LGBCycleScrollView', :path => '../'

  
end
